### PR TITLE
fixed import to be explicite relative - python 3 compatibility - clos…

### PR DESCRIPTION
**Pull request by fizyk**
…es #20

### CODE REVIEW

**Comment by twolfson** [comment]
Weird, I thought we were using relative imports but it seemed to have snuck through on #19. /cc @pwilczynskiclearcode 

https://github.com/twolfson/restructuredtext-lint/commit/78d705ebd0da7cc771b628795396d4ba3b77e94b#diff-e949ffe373262eec34e1a21f14ffcfa4L5

I will land this by the end of the weekend. For now, you can use an older version which uses relative imports (e.g. `0.11.3`):

https://github.com/twolfson/restructuredtext-lint/blob/0.11.3/restructuredtext_lint/cli.py#L5

**Comment by twolfson** [comment]
Ah, Travis CI is failing due to not being installed as a development package. Can you add a `python setup.py develop` to Travis CI?

**Comment by twolfson** [comment]
Oh, never mind. It is there, strange. Can you update the `from lint` to a `from restructuredtext_lint.lint`?

```python
from restructuredtext_lint.lint import lint_file
```

**Comment by fizyk** [comment]
sure

**Comment by fizyk** [comment]
updated both in cli module and in init to have them same throughout the package

**Comment by twolfson** [comment]
Ah, thank you =) I too appreciate consistency. I still have the same ETA for the end of this weekend.

**Comment by fizyk** [comment]
no problem :)

**Comment by twolfson** [comment]
I wound up finding some free time tonight. This has been landed/released in `0.12.2`. Thanks again for the patch =)

**Pull request merged**
