### PR TITLE
Add Other Tools section in README

### PR DESCRIPTION
**Pull request by nvuillam**
Add **Other Tools Integration** section, with links to :

- [Mega-Linter](https://nvuillam.github.io/mega-linter/) : see [rst-link page](https://nvuillam.github.io/mega-linter/descriptors/rst_rst_lint/)
- [SublimeLinter-rst](https://github.com/SublimeLinter/SublimeLinter-rst)

### CODE REVIEW

**Comment by twolfson** [comment]
Ah, great idea! I'm a little weary about putting hardcoded references in the repo though. It would make project maintainers gatekeepers, and theoretically could create README bloat

Could you make this a wiki page and we'll reference that from the README?

**Comment by nvuillam** [comment]
Sorry, my english capability has its flaws (I'm french ^^)
Do you mean that you would like a wiki page on restructuredtext-lint repo or on Mega-Linter repo ?
- If 1, do I have the rights to do that on your repo ?
- If 2, informations are described in a [YML file](https://github.com/nvuillam/mega-linter/blob/1194036b387a706f3497d52685b5f817e12ed446/megalinter/descriptors/rst.yml#L7) then used to build dynamic info and generate online documentation, so I can't really put that in a wiki, but checks for dead links are implemented, + dynamic infos (like help) are refreshed when necessary

Please let me know :)

**Comment by twolfson** [comment]
Not a problem =) I can't speak of word of French so you're way ahead of me there

Yes, I'd like a wiki page on restructuredtext-lint

The main repo and the wiki repo don't share rights. Wiki repos are set to public by default (like Wikipedia), I could lock it down but I don't

https://github.com/twolfson/restructuredtext-lint/wiki

Once the page is set up, then I'll add a section and reference to it in the main README

Does that work for you?

**Comment by twolfson** [comment]
I might also be entirely wrong about the public wiki permissions. If you don't see a way to add a page, then let me know

**Comment by nvuillam** [comment]
Done ;)

https://github.com/twolfson/restructuredtext-lint/wiki/Integration-in-other-tools

**Comment by twolfson** [comment]
Wonderful! Looks great! I'm heads down on another task at the moment but should get to adding a section + link to the README soon

Thanks for being flexible =D

**Comment by twolfson** [comment]
Alright, the new section has been added and we've published to PyPI for distributed info. Thanks again for your help on this! =D

https://github.com/twolfson/restructuredtext-lint/wiki/Integration-in-other-tools

**Pull request closed without merging**
