### PR TITLE
add support for Python 3.7

### PR DESCRIPTION
**Pull request by Jenselme**
Original patch by Miro Hrončok. See https://bugzilla.redhat.com/show_bug.cgi\?id\=1605884

### CODE REVIEW

**Comment by Jenselme** [comment]
I think we can wait a bit for Python 3.7 on travis. It should come soon.

**Comment by twolfson** [comment]
Cool, works for me. Leaving this PR open until then

**Comment by dotlambda** [comment]
Any updates?

**Comment by twolfson** [comment]
In theory it should work as Travis CI has 3.7 support, https://docs.travis-ci.com/user/languages/python/, but I'm still seeing errors. It looks like `__dir` is being picked up as a class-level variable due to its `__` prefix and the 3.7 build is failing to compile `PyYAML`

@dotlambda If this is high priority for you, then I'm happy to accept a PR which only updates the library to stop using `__dir__` (e.g. moves to `_dir`) and passes existing Python versions

**Comment by Jenselme** [comment]
@twolfson @dotlambda I just updated this PR and travis build passed!

**Comment by twolfson** [comment]
Great, thanks @Jenselme! Landing this now

**Comment by twolfson** [comment]
This has been landed in `1.3.0` and pushed to PyPI. Thanks again!

**Comment by Jenselme** [comment]
You're welcomed! And thanks for your package!

**Pull request merged**
